package org.example.app;

import org.example.infrastructure.annotation.Component;

@Component
public class BetterEmailSender implements EmailSender {
    @Override
    public void send(String to, String subject, String body) {
        System.out.printf(
                "Sending email to %s. Subject: %s. Body: %s\nEmail generated by BetterEmailSender\n",
                to,
                subject,
                body
        );
    }
}
